### ISSUE TITLE
Testing the model

### ISSUE THREAD

**Issue by melgor** [da03/Attention-OCR#20]
Hi, I have just run the new version of your code (TF and Keras) at my dataset.
The perplexity is ~ 1.3, which is very nice. But when I want to test the model I get ~1000.
After looking into visualization it look like the model always predict the same sequence of letters, no matter what input is (both on train test and validation set which the model did not see). 

This is my command which I use for testing:
```bash
python src/launcher.py --phase=test --data-path=/home/ubuntu/Data/anno_v2/labels_vals.txt --data-base-dir=/home/ubuntu/Data/anno_v2 --log-path=logtest.txt --load-model --visualize
```
In the other hand, when I continue training, everything is ok. The only think which vary between this two runs is 'decoder' input: while testing it is predicted words from previous iterations while in 'train' it is ground truth.
Do you know what goes wrong? Or I overfitt to data and now first letter does create a all sequence, no matter what input is (my data have 15k examples)?

**Comment by da03** [comment]
Hmm thanks for the feedback! Can you test the model on the training data as well? 15k examples seem to be small, but it's also possible that there be bugs in my code.

**Comment by melgor** [comment]
In train dataset there is same situation. I am trying to investigate it now
but still no conclusions.

Maybe there is a bug which cause that your pretrained model does not work
while testing with new version of code.

**Comment by da03** [comment]
Okay I'll look into it. Also looking forward to your solving the problem!

**Comment by Yang507** [comment]
I use my data(ID card numbers:0~9 and 'X') to train and get the model, when I test my data with my model, there are still some same bugs occur:
    
    ~/anaconda2/Attention-OCR-master/src/model/model.py:380: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
      attention = attentions[idx][:(real_len/4-1)]
    ~/anaconda2/Attention-OCR-master/src/model/model.py:387: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
    attention_orig[i] = attention[i/4-1]
     Traceback (most recent call last):
     File "src/launcher.py", line 129, in <module>
    main(sys.argv[1:], exp_config.ExpConfig)
     File "src/launcher.py", line 126, in main
      model.launch()
     File "~/anaconda2/Attention-OCR-master/src/model/model.py", line 208, in launch
      for batch in self.s_gen.gen(self.batch_size):
     File "~/anaconda2/Attention-OCR-master/src/data_util/data_gen.py", line 65, in gen
    img_bw, word = self.read_data(img_path, lex)
    File "~/anaconda2/Attention-OCR-master/src/data_util/data_gen.py", line 117, in read_data
    assert ord(c) > 87 or 47 < ord(c) < 58
    AssertionError

I had changed model.py and data_gen.py file ,like modify `#assert 96 < ord(c) < 123 or 47 < ord(c) < 58` `assert ord(c)>87 or 47 < ord(c) <58`. The output result is very bad.

**Comment by melgor** [comment]
@da03 
I have made a small test and get the visualization of data during training. And results here are correct, model predict different output based on input. But the attention visualization does not work, I get some random position of attention.

Second test which I done is comparing the CNN output in test and train phase. And sum of all activation while training is 10^5, while testing it is 10^2 (while most of features are zeros). So it look like CNN was not loaded correctly. 
I don't know Keras as good and I do not know why. I'm planning to remove the Keras dependence from this code and use tf.slim instead. Then it should be easier to maintain and everything should work.

@Yang507 
I think that your problem is related to my. Sth is wrong then model is test phase and model just output random sequences (in my case always the same with very small variation)

**Comment by da03** [comment]
Wow thanks for the input! I'll try to figure that out. The version is really an issue, since I started to write this implementation in June, while now everthing gets broken up...

**Comment by da03** [comment]
Hi guys, I just updated the code to support using the provided model. You need to add a command line flag `--old-model-version` in order to use my pretrained model. Now everythin should work fine, and if you do not use my provided model, do not add this flag.

What happened to Keras is that they changed the definition of their `runn_std` in the batch normalization layer. Now their `running_std` is actually the variance, while at the time we trained our model, `running_std` is the standard deviation, as the name suggested.

**Comment by melgor** [comment]
Hi. Thanks for an update.
I have created the Tf-SLIM version (so without the Keras) but this does not resolved my situation. I get just faster convergence (I do not why) and nice error on train set. It look like that I was over-fitting into train set. Then I started to analyse your code and I have found the issue related to my dataset, it is bucketing. I was using batch-size = 64, so 'bucket'  need to find the 64 images of same size. My images width are from 300 to 800, so it is really hard to find exactly the same width. So making the batch-size smaller (8) give me much better results.

Now I'm trying to refactor your code to make bucketing less sensitive to variation of images in train set. Here is my idea:

1. First analyse all the images and to each bucket assign the images. The number of buckets is low (5-6).
2. GetBatch function choose random bucket and then random images from bucket. This images are padded with zeros to match the size of bucket. For each image save a mask of original image.
3. Run a CNN on it. 
4. Run a BiRNN on it.
5. Use mask to zero the output of BiRNN which was padded.
6. Use decoder with targets.

So, I would like to use original Seq2Seq idea from tensorflow about 'buckets' and then write rest of the code. But it look like that you need to make more changes is original Seq2Seq than I thought, so I need to figure-out what you have done in code and what was a purpose. 

Some question:
 

1. Why the output of CNN is reshaped to [batch_size, width*height of last features map, num_features]?  I think it should be different [batch_size, num_features*width of last features map, height of last features] map], so in next iteration of RNN you are going from left to right by single line. Currently you use several lines at once. Do you have any reason for that? I think this is why your attention does not surrounds the letter, but just start at beginning of it (but this maybe a visualization misunderstanding). 

2. Line: https://github.com/da03/Attention-OCR/blob/master/src/model/seq2seq_model.py#L105   As I understand, you want to zero the encoder input as you add zero padding, right? It is really necessary, did you try training with it?

**Comment by nshmyrev** [comment]
This bucket-by-width approach is not very reasonable overall. We implemented bucket-by-image-width approach where you simply decide on image size, not on the text size. You have to extend image background to tied images in the bucket together then, it works better than current approach.

**Comment by da03** [comment]
@melgor 1. Note that when we are using buckets, we would reshape the image to the smallest bucket that can hold it. So I think that it's unnecessary to reimplement anything, you can simply use less buckt specifications (In file data_utils/data_gen.py). For example, if you simply use 1 bucket, all images would be reshaped to this size.
2. Yes. It's the correct thing to do things (our model should not be modified just because we want a simple implementation, unless there are better reasons). But I heard that without doing so would work.

**Comment by da03** [comment]
@nshmyrev We do not understand why the bucket-by-text-length is not reasonable. In the current implementation, we are doing bucketing both over image aspect ratio and over text length. Admittedly, with enough GPU memory, it is best to not do a bucketing over text length, but you can simply modify the bucketing specifications in our code such that the text length in each bucket is set to the maximum allowed value, then our code reduce to the only-bucketing-by-aspect-ratios case.

**Comment by melgor** [comment]
It look like the Issue is resolved: 
1. Testing now works great
2. I found the reason of very low test results.

**Comment by Yang507** [comment]
@melgor How did you do it? I tested my data  very bad.

**Comment by melgor** [comment]
As I said earlier, it looks that model was over-fitting to train data. The main reason was is the current 'bucket' implementation (where we have two types of bucket: 'bucket-image' and 'bucket-encoder'). The number of 'bucket-image' is defined for max_width of image, the number of 'bucket-encoder' is ~5. 
This is the idea of bucketing in that code (how I understand it):
**For each example in epoch:**
  1.  Read image, encode text
  2.  Insert image to the bucket-image with same width
  3.  Check if chosen bucket-image have enough image for batch (==batch_size). 
      3.1 If yes,  create padding of features from images after CNN to match first bigger "bucket-encoder". Then run the iteration.
     3.2 If there is no enough images in bucket-image, then  read next example.

**My explanation:** 
In normal training the number of iterations == train_size/batch_size. In this repo there will be not such situation, mainly because we need to fill bucket-image with 'batch_size' images to make use of them. And image situation where you have images with width [100,800] (this was my situation), so you create the 700 'bucket-image'. And you need 'batch_size' images of exactly same to make use of it. 

**My case:**
I was training the model with batch-size = 64, 15k images. So on average there is 21 images per bucket. As 21 < 64, most of  'bucket-image' was not used, so we can approximate that we train on ~5k images. When I test such model on validation set, I get very bad results.
In the other hand, when I use batch-size = 4, I used almost all of the 'bucket-image' and model at validation was comparable to train.

**Last note about generalization:**
To sum up my test case, it look like I need to go better understand all process. I was compering two different architecture for OCR. CNN-BiLSMT-CTC and Attention-Encoder-Decoder. The training results are pretty much the same. But the generalization of Attention-Encoder-Decoder is awful, really no useful results. For example, when it is used to decode the words which it does not seen during training, it predict one of the words from training set (as CNN-BiLSMT-CTC  does not have such problem). I think this is because of 'generation' process of decoder. I was thinking that it is because of overfitting, so I added DropOut after CNN and in BiLSMT-Encoder, but this does not work at all. Also visualization of attention for new cases looks very strange (it does not analyse letter by letter, but jumps from one side to other). If anybody know why this happened, please let me know.

**Comment by Duanexiao** [comment]
@da03 hello, can you tell me the command line to run the test dataset on your provided model?when I run the command line like this :python src/launcher.py --phase=test --visualize --data-path=evaluation_data/svt/test.txt --data-base-dir=evaluation_data/svt --log-path=log.txt --model-dir=model --output-dir=results --old-model-version  It tells me that :launcher.py: error: unrecognized arguments: --old-model-version

**Comment by da03** [comment]
hi @Duanexiao the current version comes from a pull request #35 to reflect tensorflow updates, so it does not support my old versioned model anymore. In order to test, you may have to train a model yourself. I'm sorry for not being able to keep up with tensorflow's updates (frequently moving functions, swapping function arguments, I've decided to move to torch) and any contributions are welcome and appreciated.

**Comment by Duanexiao** [comment]
@da03 ok,thank you all the same.can you tell me the test accuracy on these test dataset by your provided model?I change some of the code to adative to the Chinese word,but the performance is not so good as I expected.

**Comment by ducanh841988** [comment]
@melgor  Do you test generalization problem in the new code?
Thanks

**Comment by zoe218** [comment]
@Duanexiao Can I speak Chinese? 您用这个模型训练好了中文吗？

**Comment by zoe218** [comment]
@melgor Hello, Just change the batch_size can solve the issue?

**Comment by melgor** [comment]
@zoe218 @ducanh841988 I've write the similar code from scratch using TF 1.4 with Seq2Seq API and I have no such problem any more. However it still exist when I use Encoder-Decoder architecture without Attention. 
I'm not sure if this bug still occur in this code or it have just been my bad. You need to try it yourself.

**Comment by zoe218** [comment]
@melgor Thank you~Happy new year!

**Comment by jameswan** [comment]
> python src/launcher.py --phase=test --data-path=/home/ubuntu/Data/anno_v2/labels_vals.txt --data-base-dir=/home/ubuntu/Data/anno_v2 --log-path=logtest.txt --load-model --visualize


For inferencing, what is the format of labels_vals.txt ?
is it just a list of the image files, since there isn't any labels on unseen data ?
